### ISSUE TITLE
Unable to add into PCL project

### ISSUE THREAD

**Issue by CliffCawley** [gabornemeth/XamMapz#1]
I'm using a PCL and upon trying to install I get:

Could not install package 'XamMapz 0.3'. You are trying to install this package into a project that targets 'portable-net45+win+wp80+MonoTouch10+MonoAndroid10+xamarinmac20+xamarinios10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Any chance you can add support?

**Comment by gabornemeth** [comment]
Are you trying to install as Nuget package? Currently you cannot make it into a PCL project. You can install as Nuget package into an Android or an iOS project. I'm going to investigate this issue. It makes sense to install the PCL part of XamMapz into a PCL project.
Curently what you can do is to download the source code from GitHub, add reference of XamMapz to you PCL project, and references of both XamMapz and XamMapz.Droid/XamMapz.iOS to your main project.

**Comment by CliffCawley** [comment]
Yes, I was trying to install as Nuget. It would be good to support PCL in nuget package too :)

Sure, in the mean time I can use the source directly but it would be good to have a nuget package for stable version use

**Comment by gabornemeth** [comment]
I have uploaded a new version of the Nuget package: 0.3.1
Please let me know whether it's working for you.

**Comment by CliffCawley** [comment]
Yes it works great now for the PCL, thank you! Unfortunately the Droid project is broken because you're using v27 of the google services.

Xamarin.Forms (2.0.1.6505) and Xamarin.Forms.Maps (2.0.1.6505) only work on v26 so when attempting to install the nuget package on the Android project, I get:  

`Updating 'Xamarin.GooglePlayServices.Maps 26.0.0.0' to 'Xamarin.GooglePlayServices.Maps 27.0.0.0' failed. Unable to find a version of 'Xamarin.Forms.Maps' that is compatible with 'Xamarin.GooglePlayServices.Maps 27.0.0.0'.`

The full Package Console log is:

`Adding XamMapz...
Attempting to resolve dependency 'Xamarin.Android.Support.Design (≥ 23.0.1.3)'.
Attempting to resolve dependency 'Xamarin.Android.Support.v7.AppCompat (≥ 23.0.1.3)'.
Attempting to resolve dependency 'Xamarin.Android.Support.v4 (≥ 23.0.1.3)'.
Attempting to resolve dependency 'Xamarin.Android.Support.v7.CardView (≥ 23.0.1.3)'.
Attempting to resolve dependency 'Xamarin.Android.Support.v7.MediaRouter (≥ 23.0.1.3)'.
Attempting to resolve dependency 'Xamarin.Forms (≥ 1.5.1.6471)'.
Attempting to resolve dependency 'Xamarin.Forms.Maps (≥ 1.5.1.6471)'.
Attempting to resolve dependency 'Xamarin.GooglePlayServices.Maps (= 26.0.0.0)'.
Attempting to resolve dependency 'Xamarin.GooglePlayServices.Base (≥ 26.0.0.0)'.
Attempting to resolve dependency 'Xamarin.GooglePlayServices.Base (≥ 27.0.0)'.
Attempting to resolve dependency 'Xamarin.GooglePlayServices.Basement (≥ 27.0.0.0)'.
Attempting to resolve dependency 'Xamarin.GooglePlayServices.Maps (≥ 27.0.0)'.
Updating 'Xamarin.GooglePlayServices.Maps 26.0.0.0' to 'Xamarin.GooglePlayServices.Maps 27.0.0.0' failed. Unable to find a version of 'Xamarin.Forms.Maps' that is compatible with 'Xamarin.GooglePlayServices.Maps 27.0.0.0'.`

**Comment by gabornemeth** [comment]
Thank you for your response. I'm aware of the Android problem, gonna fix it soon.

**Comment by gabornemeth** [comment]
I have uploaded version 0.3.2. Downgraded Google Play Services to 26.0.0

**Comment by CliffCawley** [comment]
Great, adds for all my projects now, tomorrow I will start using it, thanks!!
